### ISSUE TITLE
Generate cjs instead of js

### ISSUE THREAD

**Issue by dnlklmn** [nado1001/style-dictionary-tailwindcss-transformer#219]
Hey @nado1001 thanks so much for this, immensely helpful.

I would love to be able to generate the tailwind config as .cjs too, but can't figure out my way around your build system somehow :)

Would that be something you could add you think?

**Comment by nado1001** [comment]
Hi @dnlklmn, thank you for raising the issue.
Currently, we do not support generation in the cjs format. We plan to support it in the future, so please wait a little longer. 
Alternatively, we also welcome pull requests for adding new features!

**Comment by nado1001** [comment]
@dnlklmn 
This feature is released in version [1.3.0](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/releases/tag/v1.3.0).
Please update your package version and try to generate in 'cjs' format.
