### ISSUE TITLE
`DEFAULT` theme keys being lowercased 

### ISSUE THREAD

**Issue by davidkelley** [nado1001/style-dictionary-tailwindcss-transformer#266]
Hi,

Thanks for a great library. I'm in the middle of implementing this for our theme, but have noticed that the `DEFAULT` keyword is being lowercased inside the output. Tailwind needs this to be uppercased, so that we can make use of class names such as `bg-orange` for example. Are you able to help?

https://github.com/tailwindlabs/tailwindcss.com/issues/1114
https://v2.tailwindcss.com/docs/upgrading-to-v2#update-default-theme-keys-to-default

**Comment by nado1001** [comment]
Hi, @davidkelley 
Thank you for raising the great issue!
The "DEFAULT" theme key is now supported in version [1.3.2](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/releases/tag/v1.3.2).
Please update your package version and check it.
We are also testing this on the [example](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/commit/ec05ada011da10aff5ac2d3fce9ce5d4b676d894), so you can check it out in conjunction with the [example](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/commit/ec05ada011da10aff5ac2d3fce9ce5d4b676d894) if you like.

**Comment by davidkelley** [comment]
Thanks very much @nado1001. Really useful library, great work!

**Comment by nado1001** [comment]
@3CordGuy 
Sorry for the delay in noticing the issue.
Can you show us the whole source code in your repository, codesandbox, etc., so that we can get a better understanding of the issue here?

**Comment by 3CordGuy** [comment]
I ended up rolling with another solution. Thanks for responding, though. I appreciate you putting this library out there.
