### ISSUE TITLE
Export getTailwindFormat

### ISSUE THREAD

**Issue by jorenbroekema** [nado1001/style-dictionary-tailwindcss-transformer#311]
This package generates a complete Style-Dictionary config, but actually the core functionality is getting the tailwind format.

It would make this package a lot more flexible and easy to use if the `getTailwindFormat` function was exported, so users can call it themselves and control the rest of their config themselves.

**Comment by nado1001** [comment]
@jorenbroekema 
This feature was released in [v1.4.0](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/releases/tag/v1.4.0).
Thank you!
