### ISSUE TITLE
add option to not extend config

### ISSUE THREAD

**Issue by shedali** [nado1001/style-dictionary-tailwindcss-transformer#345]
could be useful to have a flag to export a tailwind config with  theme.colors rather than theme.extend.colors - for when people want to constrain the options

**Comment by pivotpointux** [comment]
@nado1001 This is  a great tool, thanks! I agree with @shedali - is it possible to control if style-dictionary-tailwindcss-transformer adds keys/values under an extend key or not? Is there a current work around?

**Comment by pivotpointux** [comment]
Added a PR for this [here](https://github.com/nado1001/style-dictionary-tailwindcss-transformer/pull/349).
