### ISSUE TITLE
Add a sample using Figma Tokens

### ISSUE THREAD

**Issue by nado1001** [nado1001/style-dictionary-tailwindcss-transformer#46]

**Comment by RWOverdijk** [comment]
This would be great! I just found this and I like the idea but I am not sure if I understand correctly.

Could this drive _everything_ in tailwind like padding/margin classes, font-size classes etc? Or can this only add new variables to tailwind?

**Comment by nado1001** [comment]
@RWOverdijk 
Sorry for the delay in noticing your comment.
The issue is that the json output from Figma Tokens, a Figma plugin, is used to generate the tailwindcss configuration file.
The detailed instructions are in the following codesandbox if you are interested.
https://codesandbox.io/s/style-dictionary-tailwind-figma-tokens-example-j83l6m

**Comment by nado1001** [comment]
@RWOverdijk
Sorry for the delay in noticing your comment.
The issue is that the json output from Figma Tokens, a Figma plugin, is used to generate the tailwindcss configuration file.
The detailed instructions are in the following codesandbox if you are interested.
https://codesandbox.io/s/style-dictionary-tailwind-figma-tokens-example-j83l6m
